Test 29

diff --git a/.github/actions/openvic-sim-release/action.yml b/.github/actions/openvic-sim-release/action.yml
--- a/.github/actions/openvic-sim-release/action.yml
+++ b/.github/actions/openvic-sim-release/action.yml
@@ -26,13 +26,32 @@ inputs:
     description: Pre-release
     type: boolean
     required: true
-  token:
-    description: Github Token to publish to target
+  src-token:
+    description: Github token for source repository
     required: true
+  target-token:
+    description: Github token for target repository
+    required: false
+    default: ''
 
 runs:
   using: composite
   steps:
+    - name: Copy src-token to env.TARGET_TOKEN
+      if: inputs.target == 'OpenVic-Simulation'
+      shell: bash
+      run: echo "TARGET_TOKEN=${{ inputs.src-token }}" >> $GITHUB_ENV
+
+    - name: Copy target-token to env.TARGET_TOKEN
+      if: inputs.target != 'OpenVic-Simulation'
+      shell: bash
+      run: |
+        if [[ -z "${{ inputs.target-token }}" ]]; then
+          echo "::error file=.github/actions/openvic-sim-release/action.yml,line=50,endLine=50::target-repo was set to a different repository and the target-token was not set."
+          exit 1
+        fi
+        echo "TARGET_TOKEN=${{ inputs.target-token }}" >> $GITHUB_ENV
+
     - name: Remove refs/tags from to-ref
       if: contains(inputs.to-ref, 'refs/tags')
       shell: bash
@@ -42,7 +61,7 @@ runs:
       if: inputs.snapshot-release == 'false' && inputs.nightly-release == 'false'
       uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
       env:
-        GITHUB_TOKEN: ${{ inputs.token }}
+        GITHUB_TOKEN: ${{ inputs.src-token }}
       with:
         configuration: ".github/actions/openvic-sim-release/release-notes-configuration.json"
         toTag: ${{ contains(inputs.to-ref, 'refs/tags') && env.TO_TAG || inputs.to-ref }}
@@ -53,7 +72,7 @@ runs:
       if: inputs.snapshot-release == 'true' && inputs.nightly-release == 'false'
       uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
       env:
-        GITHUB_TOKEN: ${{ inputs.token }}
+        GITHUB_TOKEN: ${{ inputs.src-token }}
       with:
         configuration: ".github/actions/openvic-sim-release/snapshot-release-notes-configuration.json"
         toTag: ${{ contains(inputs.to-ref, 'refs/tags') && env.TO_TAG || inputs.to-ref }}
@@ -64,7 +83,7 @@ runs:
       if: inputs.nightly-release == 'true' && inputs.snapshot-release == 'false'
       uses: mikepenz/release-changelog-builder-action@348e88fab4c37338b1e803ceb2d4a7a5db6c0833 # v6.2.2
       env:
-        GITHUB_TOKEN: ${{ inputs.token }}
+        GITHUB_TOKEN: ${{ inputs.src-token }}
       with:
         configuration: ".github/actions/openvic-sim-release/nightly-release-notes-configuration.json"
         toTag: ${{ contains(inputs.to-ref, 'refs/tags') && env.TO_TAG || inputs.to-ref }}
@@ -126,4 +145,4 @@ runs:
         prerelease: ${{ inputs.prerelease }}
         draft: ${{ inputs.snapshot-release == 'false' && inputs.nightly-release == 'false' }}
         repo: ${{ inputs.target }}
-        token: ${{ inputs.token }}
+        token: ${{ env.TARGET_TOKEN }}
diff --git a/.github/workflows/nightly-releases.yml b/.github/workflows/nightly-releases.yml
--- a/.github/workflows/nightly-releases.yml
+++ b/.github/workflows/nightly-releases.yml
@@ -141,10 +141,39 @@ jobs:
         with:
           fetch-depth: 1 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
 
+      - name: Get FROM_REF based on latest master/nightly
+        run: |
+          LAST_MASTER_TAG=$(gh release list -L 1 --json tagName --jq '.[0]')
+          LAST_NIGHTLY_TAG=$(gh release list -L 1 -R OpenVicProject/${{ env.TARGET_REPO }} --json tagName --jq '.[0]')
+
+          LAST_MASTER_TAG_CREATED_DATE=$(jq -r --args ".createdAt" $LAST_MASTER_TAG)
+          LAST_NIGHTLY_TAG_CREATED_DATE=$(jq -r --args ".createdAt" $LAST_NIGHTLY_TAG)
+
+          LAST_MASTER_TAG_CREATED_SEC=$(date -d $LAST_MASTER_TAG_CREATED_DATE +%s)
+          LAST_NIGHTLY_TAG_CREATED_SEC=$(date -d $LAST_NIGHTLY_TAG_CREATED_DATE +%s)
+
+          if [ $LAST_MASTER_TAG_CREATED_SEC -gt $LAST_NIGHTLY_TAG_CREATED_SEC ]; then
+            echo "FROM_REF=$(jq -r --args ".tagName" $LAST_MASTER_TAG)" >> $GITHUB_ENV
+          else
+            TAG_TO_FIND=$(jq -r --args ".tagName" $LAST_NIGHTLY_TAG)
+            SHORT_HASH_OF_TAG=$(echo $TAG_TO_FIND | awk -F "[@]+" '/Generated from: OpenVicProject\\/OpenVic-Simulation@[a-zA-Z0-9]+/{print $2}')
+            COMMIT_HASH=$(git rev-parse --verify -q $SHORT_HASH_OF_TAG)
+
+            if [ -z "$COMMIT_HASH" ]; then
+              echo "::error file=.github/workflows/nightly-releases.yml,line=163,endLine=163::Could not find commit for short hash $SHORT_HASH_OF_TAG."
+              exit 1
+            fi
+
+            echo "FROM_REF=$COMMIT_HASH" >> $GITHUB_ENV
+          fi
+
       - name: Publish Nightly Release
         uses: ./.github/actions/openvic-sim-release
         with:
-          prerelease: true
+          latest: true
+          nightly-release: true
+          from-ref: ${{ env.FROM_REF }}
           target-repo: ${{ github.env.TARGET_REPO }}
-          token: ${{ secrets.GITHUB_TOKEN }}
+          src-token: ${{ secrets.GITHUB_TOKEN }}
+          target-token: ${{ secrets.GITHUB_TOKEN }}
 
